### PR TITLE
enable capability to install per user + doc

### PR DESCRIPTION
**Pull request by douph1**
To close https://github.com/AdoptOpenJDK/openjdk-installer/issues/103

### CODE REVIEW

**Comment by douph1** [comment]
test job running
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/standalone_create_installer_windows/77/console

**Comment by douph1** [comment]
do not merge, I wait the result from the test job

**Comment by karianna** [comment]
> do not merge, I wait the result from the test job

How did the test job go?

**Comment by douph1** [comment]
Test job build success, but I want to test it a little more, and build another one with newer OpenJDK to test upgrade

**Comment by douph1** [comment]
Updated job success with build 8u212-b03
MSI upgrade from 8u202-b08 to 8u212-b03 works

Is someone other want to per user msi install or I can merge ?

**Comment by alexhass** [comment]
Guys, that a shit is this, please? per user installer with internal detection?

```
<InstallExecuteSequence>
        <Custom Action="PerMachineInstall" Before="CostFinalize">ALLUSERS=1  OR (ALLUSERS=2 AND Privileged)</Custom>
        <Custom Action="PerUserInstall"    Before="CostFinalize">ALLUSERS="" OR (ALLUSERS=2 AND (NOT Privileged))</Custom>
    </InstallExecuteSequence>
```

How often should this fail and cause incorrect installations? Please DO NOT IMPLEMENT per USER SHIT.

**Comment by karianna** [comment]
> Guys, that a shit is this, please? per user installer with internal auto detection?
> 
> ```
> <InstallExecuteSequence>
>         <Custom Action="PerMachineInstall" Before="CostFinalize">ALLUSERS=1  OR (ALLUSERS=2 AND Privileged)</Custom>
>         <Custom Action="PerUserInstall"    Before="CostFinalize">ALLUSERS="" OR (ALLUSERS=2 AND (NOT Privileged))</Custom>
>     </InstallExecuteSequence>
> ```
> 
> How often should this fail and cause incorrect installations? Please DO NOT IMPLEMENT per USER SHIT.
> 
> Keep https://www.hass.de/content/developers-best-practice-windows-user-profiles this in mind and suxxx [wixtoolset/issues#5908](https://github.com/wixtoolset/issues/issues/5908)

@alexhass Please keep the tone of communications to technical concerns, we have an expected level of civil communication at Adopt.

**Comment by gdams** [comment]
@alexhass I have removed your previous comment. This is the second time I have had to remove a comment of yours due to bad language. Please consider the wider community when commenting on issues at AdoptOpenJDK.

**Pull request merged**
