### PR TITLE
Merge cmd script into one/enable cache/check error

### PR DESCRIPTION
**Pull request by douph1**
- Merge multiple cmd script into one
- Add error handling
- Add Cache for faster multilanguage msi build
- Postpone msi validation

### CODE REVIEW

**Comment by gdams** [comment]
This PR will require the build scripts in Jenkins to be updated. Please bear this in mind before landing

**Comment by karianna** [comment]
> This PR will require the build scripts in Jenkins to be updated. Please bear this in mind before landing

Where are those build scripts currently?  Do we have them extracted to a GitHub repo?

**Comment by alexhass** [comment]
Caching and reusing MST fIles can cause many troubles. We need to make sure they are recompiled if a translation change and/or the main xml uses a string in a different feature. I‘m interrested how you‘d like to make this a build reliable than...

I‘m also looking forward to the single cmd... that was split as I have no idea how to do without duplicating code. We should think about building for 40 languages...

**Comment by douph1** [comment]
@alexhass

**Comment by alexhass** [comment]
Cool :-) many thanks for this tip.

**Pull request merged**
