### PR TITLE
WIP: add javafx support for macOS

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Comment by aahlenst** [comment]
There's no free LTS support for OpenJFX, so we'd end bundling an outdated OpenJFX that possibly contains security issues.

I suggest we close this one.

**Comment by karianna** [comment]
> There's no free LTS support for OpenJFX, so we'd end bundling an outdated OpenJFX that possibly contains security issues.
> 
> I suggest we close this one without merging. What do you think, @gdams?

We're especially concerned with OpenJFX 8 not being supported.  Is that also true of OpenJFX 11 though?  I thought the LTS patches continued there..

**Comment by karianna** [comment]
@gdams - needs a rebase as well.

**Comment by aahlenst** [comment]
@karianna On https://github.com/openjdk/jfx, the last tag I found that involved JDK 11 was this one:

```
* 2018-08-28 19:00:45 -0700 ee351e5ba6  (tag: 11+26)
```

Run `git log --date-order --graph --tags --simplify-by-decoration --pretty=format:'%ai %h %d'` on the OpenJFX repository to get the same output. The entirety of branches:

```
origin/HEAD -> origin/master
origin/jfx14
origin/master
```

I haven't seen another repository with `jfx` in the name on https://github.com/openjdk/jfx that would match and there's no activity on https://hg.openjdk.java.net/openjfx either. 

The [last publicly available version provided by Gluon](https://gluonhq.com/products/javafx/) is 11.0.2. There's an 11.0.6, but only for paying customers. On Maven Central, [there isn't anything newer than 11.0.2 either](https://search.maven.org/artifact/org.openjfx/javafx).

I don't know where else to look.

**Comment by karianna** [comment]
> @karianna On https://github.com/openjdk/jfx, the last tag I found that involved JDK 11 was this one:
> 
> ```
> * 2018-08-28 19:00:45 -0700 ee351e5ba6  (tag: 11+26)
> ```
> 
> Run `git log --date-order --graph --tags --simplify-by-decoration --pretty=format:'%ai %h %d'` on the OpenJFX repository to get the same output. The entirety of branches:
> 
> ```
> origin/HEAD -> origin/master
> origin/jfx14
> origin/master
> ```
> 
> I haven't seen another repository with `jfx` in the name on https://github.com/openjdk/ that would match and there's no activity on https://hg.openjdk.java.net/openjfx either.
> 
> The [last publicly available version provided by Gluon](https://gluonhq.com/products/javafx/) is 11.0.2. There's an 11.0.6, but only for paying customers. On Maven Central, [there isn't anything newer than 11.0.2 either](https://search.maven.org/artifact/org.openjfx/javafx).
> 
> I don't know where else to look.

Thanks for checking, yes, in that case, I think we should provide clear instructions on how to bundle, but not automatically bundle ourselves.  I'll let the TSC vote though.

**Comment by aahlenst** [comment]
Instructions plus FAQ are in place: https://adoptopenjdk.net/faq.html#openjfxfaq

**Pull request closed without merging**
