### PR TITLE
Add Dragonwell support in regex

### PR DESCRIPTION
**Pull request by joeyleeeeeee97**
Issue: https://github.com/AdoptOpenJDK/openjdk-installer/issues/279

### CODE REVIEW

**Review by douph1 — CHANGES_REQUESTED** [review]
Need too handle dragonwell in wix/Build.OpenJDK_generic.cmd L63-72 too

**Comment by douph1** [comment]
> Need two handle dragonwell in wix/Build.OpenJDK_generic.cmd L63-72 too

And add another Main.dragonwell.wxs
and add some files in wix/Lang

**Comment by joeyleeeeeee97** [comment]
> > Need two handle dragonwell in wix/Build.OpenJDK_generic.cmd L63-72 too
> 
> And add another Main.dragonwell.wxs
> and add some files in wix/Lang

Please check

**Comment by sxa** [comment]
@douph1 Are you happy with this now?

**Comment by douph1** [comment]
Yes, we need a test run from this branch for openj9/hotstpot and dragonwell

**Comment by douph1** [comment]
I don't know if and how the new PR tester work for opendjk-installer or if we must try manually with standalone_create_installer_windows job

**Review by douph1 — COMMENTED** [review]
Need job testing

**Review by sxa — COMMENTED** [review]
I'm personally ok with this too (subject to testing as Philippe says!) but since we're very close to a GA next week I propose holding off on merging until we've completed those GAs for HotSpot and OpenJ9.

**Comment by karianna** [comment]
> I'm personally ok with this too (subject to testing as Philippe says!) but since we're very close to a GA next week I propose holding off on merging until we've completed those GAs for HotSpot and OpenJ9.

@douph1 and @joeyleeeeeee97 - will it be possible to test this today?  If it's all OK we could consider merging it.

**Comment by joeyleeeeeee97** [comment]
@karianna  I cannot access installer jobs, so could someone help me trigger a test? Thanks.

**Comment by douph1** [comment]
I will try to launch test job this morning

**Comment by douph1** [comment]
I don't find build zip for Dragonwell on github so it's difficult to test it ..
I will test the non-regression for hotspot/openj9

**Comment by douph1** [comment]
OpenJ9 : Build OK https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/standalone_create_installer_windows/142/
Hotspot : Build OK https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/standalone_create_installer_windows/140/
Dragonwell : Build OK https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/standalone_create_installer_windows/148/
Just need some time to reboot on Windows and test the installer, If someone can take a look...

**Comment by douph1** [comment]
All three jre installer ok

**Review by douph1 — APPROVED** [review]

**Pull request merged**
