### PR TITLE
Changelog for Windows Installer

### PR DESCRIPTION
**Pull request by douph1**
As discuted @gdams

### CODE REVIEW

**Comment by douph1** [comment]
I have rebased this near 1year old PR ..
If interested in tracked/publish the Windows Installer change to community, please take a look and comment or reject/drop

**Comment by aahlenst** [comment]
Having a changelog is a great thing. But it does not make sense to do that only for the MSIs and not by date. The changes should either be grouped by JDK versions or by CPU dates. An "Upcoming" section is needed, too.

What was the outcome of your discussion with George?

**Comment by douph1** [comment]
- Me: What are you thinking about starting to maintain a "Changelog" for the Windows installer ?

- G: yeah that would be a really good idea! do you want to put something together?

- Me: Did we must try to recover the past history to document it ? (please say no :) )

  I just don't know how tagged the change as we don't version the installer .. there is only a master 
  branch wich is used in release
  so matchin feature add/remove with release of 8u222 or something else is difficult
 so maybe just set the changelog by date/time .. and if 8u222b12 b18 b25 is build after this date we can expect the new feature is embeded in the patch release ..

- G: lets go with no
 start from now
 and yeah do it by date

- M: last question :), do you think we must embeded the changelog in the distributed JDK directory wich is installed on the client computer ? 

- G: no I'd just keep it in github 

- Me: k

- G: unless you think embedding it makes sense

- Me: a little but i can make confusion with Changelog from OpenJDK
 Or dont naming it ChangeLog but InstallerChangelog ...
 I think it can be helpful to know what the installer is capable

- G: InstallerChangelog is probably best

- Me: if you setup Adop msi .. next next next , you go to folder and you know what is the embeded fix into this msi

- G: sounds good to me!

- Me: Ok I will try to do a draft for that later

- G: great!
thanks for all your work on the installers!

**Comment by aahlenst** [comment]
I think it makes sense to have a changelog, but it does not make sense to have one without proper releases. There's no much difference to the Git history. The problem here seems to be that we always build from master instead of tags. This also requires us to stop the development during the releases.

**Comment by douph1** [comment]
So we must start a new issue to discuss what change are required to build from tagged openjdk-installer ? right ?
How tag it ? Manually ( In sync with code freeze/ cpu date / release ) ?

**Comment by aahlenst** [comment]
I guess some discussion is going to be needed. Ideally, this effort should extend to other repositories. Apart from that, we might need to split the installer repository for Mac, Windows and Linux. This would also make sense from a testing POV. Triggering multiple hours of tests for a installer variant that hasn't changed isn't a good use of our computing resources. I've started this process for Adoptium/Linux.

**Comment by karianna** [comment]
@douph1 - Can you update this PR with the various release notes and then I think this can go in :-)

**Review by gdams — APPROVED** [review]

**Comment by douph1** [comment]
I have updated the changelog and added some clarification about the goal wich is not to duplicate commit history but grouping visible change impacting the consumer of the MSI

**Pull request merged**
