### PR TITLE
Fix JAVA_HOME setting

### PR DESCRIPTION
**Pull request by lumpfish**
Removes bin directory from end of JAVA_HOME

### CODE REVIEW

**Comment by alexhass** [comment]
I think this is not correct... java.exe is in \bin folder and not the folder up. If \bin is removed the java.exe cannot found than and you cannot issue java -version command everywhere in cmd.exe

**Comment by lumpfish** [comment]
Yes, java.exe is in /bin, so that should be added to PATH.
JAVA_HOME is used by applications (admittedly in some cases inconsistently) to locate jdk resources, not necessarily just executables.
For example: https://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/

**Comment by alexhass** [comment]
I was wrong. I will send a pull asap.

**Comment by karianna** [comment]
Thanks, @lumpfish this helped resolve a number of issues.  Closing this as superseded by #23

**Pull request closed without merging**
