### PR TITLE
Build Linux Packages

### PR DESCRIPTION
**Pull request by aahlenst**
Adds the necessary infrastructure and build scripts to build Debian (for Debian and Ubuntu) and RPM (CentOS, Fedora, RHEL, OpenSUSE, SLES) packages from binary AdoptOpenJDK distributions with the help of fpm. The exact capabilities and supported platforms are outlined in the included README.

The Debian packages should be pretty solid and conform to user expectations. I'm not so sure regarding the RPMs because everybody packages them a little differently.

What is missing and is going to be addressed in upcoming pull requests:

* Upload to package servers
* Automatic testing of packages

This pull request supersedes #61.

### CODE REVIEW

**Comment by dal00** [comment]
There is no symlink to src.zip in the root of /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/
I think a lot of tools might expect one there.

**Comment by aahlenst** [comment]
@dal00 Which distribution, package format? Where should src.zip point to?

**Comment by dal00** [comment]
Sorry, I should have been more precise.
Debian/Ubuntu
/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/lib/src.zip ->  /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/src.zip

**Comment by aahlenst** [comment]
@dal00 Thanks, should be fixed.

**Pull request merged**
